/*
 * ESPHome port: NUT variable -> HID path mapping table, extracted
 * verbatim (name/path/format pairs) from drivers/mge-hid.c
 * (mge_hid2nut[]), with conversion kinds:
 *   0 = plain numeric (HID scaling only)
 *   1 = Kelvin -> Celsius (kelvin_celsius_conversion)
 *   2 = As -> Ah (mge_battery_capacity)
 *
 * Copyright (C) 2005-2008 Arnaud Quette, and the NUT team.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */
#include "mge_map.h"

/* Entries are ordered like upstream: the first path that resolves in
 * the device report descriptor wins for a given NUT variable. */
const mge_map_entry_t MGE_READ_MAP[] = {
	{ "battery.charge", "UPS.PowerSummary.RemainingCapacity", "%.0f", 0 },
	{ "battery.charge.low", "UPS.PowerSummary.RemainingCapacityLimitSetting", "%.0f", 0 },
	{ "battery.charge.low", "UPS.PowerSummary.RemainingCapacityLimit", "%.0f", 0 },
	{ "battery.charge.restart", "UPS.PowerSummary.RestartLevel", "%.0f", 0 },
	{ "battery.capacity", "UPS.BatterySystem.Battery.DesignCapacity", "%.2f", 2 },
	{ "battery.runtime", "UPS.PowerSummary.RunTimeToEmpty", "%.0f", 0 },
	{ "battery.runtime.low", "UPS.PowerSummary.RemainingTimeLimit", "%.0f", 0 },
	{ "battery.runtime.elapsed", "UPS.StatisticSystem.Input.[1].Statistic.[1].Time", "%.0f", 0 },
	{ "battery.runtime.low", "UPS.PowerSummary.RemainingTimeLimit", "%.0f", 0 },
	{ "battery.temperature", "UPS.BatterySystem.Battery.Temperature", "%.1f", 1 },
	{ "battery.voltage", "UPS.BatterySystem.Voltage", "%.1f", 0 },
	{ "battery.voltage", "UPS.PowerSummary.Voltage", "%.1f", 0 },
	{ "battery.voltage.nominal", "UPS.BatterySystem.ConfigVoltage", "%.0f", 0 },
	{ "battery.voltage.nominal", "UPS.PowerSummary.ConfigVoltage", "%.1f", 0 },
	{ "battery.energysave.load", "UPS.PowerConverter.Input.[3].ConfigPercentLoad", "%.0f", 0 },
	{ "battery.energysave.delay", "UPS.PowerConverter.Input.[3].EnergySaving.ShutdownTimer", "%.0f", 0 },
	{ "battery.energysave.delay", "UPS.PowerConverter.Input.[3].ShutdownTimer", "%.0f", 0 },
	{ "battery.energysave.realpower", "UPS.PowerConverter.Input.[3].ConfigActivePower", "%.0f", 0 },
	{ "ups.efficiency", "UPS.PowerConverter.Output.Efficiency", "%.0f", 0 },
	{ "ups.load", "UPS.PowerSummary.PercentLoad", "%.0f", 0 },
	{ "ups.load.high", "UPS.Flow.[4].ConfigPercentLoad", "%.0f", 0 },
	{ "ups.timer.start", "UPS.PowerSummary.DelayBeforeStartup", "%.0f", 0 },
	{ "ups.timer.shutdown", "UPS.PowerSummary.DelayBeforeShutdown", "%.0f", 0 },
	{ "ups.timer.reboot", "UPS.PowerSummary.DelayBeforeReboot", "%.0f", 0 },
	{ "ups.test.interval", "UPS.BatterySystem.Battery.TestPeriod", "%.0f", 0 },
	{ "ups.temperature", "UPS.PowerSummary.Temperature", "%.1f", 1 },
	{ "ups.power", "UPS.PowerConverter.Output.ApparentPower", "%.0f", 0 },
	{ "ups.L1.power", "UPS.PowerConverter.Output.Phase.[1].ApparentPower", "%.0f", 0 },
	{ "ups.L2.power", "UPS.PowerConverter.Output.Phase.[2].ApparentPower", "%.0f", 0 },
	{ "ups.L3.power", "UPS.PowerConverter.Output.Phase.[3].ApparentPower", "%.0f", 0 },
	{ "ups.power.nominal", "UPS.Flow.[4].ConfigApparentPower", "%.0f", 0 },
	{ "ups.realpower", "UPS.PowerConverter.Output.ActivePower", "%.0f", 0 },
	{ "ups.L1.realpower", "UPS.PowerConverter.Output.Phase.[1].ActivePower", "%.0f", 0 },
	{ "ups.L2.realpower", "UPS.PowerConverter.Output.Phase.[2].ActivePower", "%.0f", 0 },
	{ "ups.L3.realpower", "UPS.PowerConverter.Output.Phase.[3].ActivePower", "%.0f", 0 },
	{ "ups.realpower.nominal", "UPS.Flow.[4].ConfigActivePower", "%.0f", 0 },
	{ "input.voltage", "UPS.PowerConverter.Input.[1].Voltage", "%.1f", 0 },
	{ "input.L1-N.voltage", "UPS.PowerConverter.Input.[1].Phase.[1].Voltage", "%.1f", 0 },
	{ "input.L2-N.voltage", "UPS.PowerConverter.Input.[1].Phase.[2].Voltage", "%.1f", 0 },
	{ "input.L3-N.voltage", "UPS.PowerConverter.Input.[1].Phase.[3].Voltage", "%.1f", 0 },
	{ "input.L1-L2.voltage", "UPS.PowerConverter.Input.[1].Phase.[12].Voltage", "%.1f", 0 },
	{ "input.L2-L3.voltage", "UPS.PowerConverter.Input.[1].Phase.[23].Voltage", "%.1f", 0 },
	{ "input.L3-L1.voltage", "UPS.PowerConverter.Input.[1].Phase.[31].Voltage", "%.1f", 0 },
	{ "input.voltage.nominal", "UPS.Flow.[1].ConfigVoltage", "%.0f", 0 },
	{ "input.current", "UPS.PowerConverter.Input.[1].Current", "%.2f", 0 },
	{ "input.L1.current", "UPS.PowerConverter.Input.[1].Phase.[1].Current", "%.1f", 0 },
	{ "input.L2.current", "UPS.PowerConverter.Input.[1].Phase.[2].Current", "%.1f", 0 },
	{ "input.L3.current", "UPS.PowerConverter.Input.[1].Phase.[3].Current", "%.1f", 0 },
	{ "input.current.nominal", "UPS.Flow.[1].ConfigCurrent", "%.2f", 0 },
	{ "input.frequency", "UPS.PowerConverter.Input.[1].Frequency", "%.1f", 0 },
	{ "input.frequency.nominal", "UPS.Flow.[1].ConfigFrequency", "%.0f", 0 },
	{ "input.transfer.low", "UPS.PowerConverter.Output.LowVoltageTransfer", "%.0f", 0 },
	{ "input.transfer.eco.low", "UPS.PowerConverter.Output.LowVoltageEcoTransfer", "%.0f", 0 },
	{ "input.transfer.bypass.low", "UPS.PowerConverter.Output.LowVoltageBypassTransfer", "%.0f", 0 },
	{ "input.transfer.boost.low", "UPS.PowerConverter.Output.LowVoltageBoostTransfer", "%.0f", 0 },
	{ "input.transfer.boost.high", "UPS.PowerConverter.Output.HighVoltageBoostTransfer", "%.0f", 0 },
	{ "input.transfer.trim.low", "UPS.PowerConverter.Output.LowVoltageBuckTransfer", "%.0f", 0 },
	{ "input.transfer.high", "UPS.PowerConverter.Output.HighVoltageTransfer", "%.0f", 0 },
	{ "input.transfer.eco.high", "UPS.PowerConverter.Output.HighVoltageEcoTransfer", "%.0f", 0 },
	{ "input.transfer.bypass.high", "UPS.PowerConverter.Output.HighVoltageBypassTransfer", "%.0f", 0 },
	{ "input.transfer.frequency.bypass.range", "UPS.PowerConverter.Output.FrequencyRangeBypassTransfer", "%.0f", 0 },
	{ "input.transfer.frequency.eco.range", "UPS.PowerConverter.Output.FrequencyRangeEcoTransfer", "%.0f", 0 },
	{ "input.transfer.hysteresis", "UPS.PowerConverter.Output.HysteresisVoltageTransfer", "%.0f", 0 },
	{ "input.transfer.trim.high", "UPS.PowerConverter.Output.HighVoltageBuckTransfer", "%.0f", 0 },
	{ "input.bypass.voltage", "UPS.PowerConverter.Input.[2].Voltage", "%.1f", 0 },
	{ "input.bypass.L1-N.voltage", "UPS.PowerConverter.Input.[2].Phase.[1].Voltage", "%.1f", 0 },
	{ "input.bypass.L2-N.voltage", "UPS.PowerConverter.Input.[2].Phase.[2].Voltage", "%.1f", 0 },
	{ "input.bypass.L3-N.voltage", "UPS.PowerConverter.Input.[2].Phase.[3].Voltage", "%.1f", 0 },
	{ "input.bypass.L1-L2.voltage", "UPS.PowerConverter.Input.[2].Phase.[12].Voltage", "%.1f", 0 },
	{ "input.bypass.L2-L3.voltage", "UPS.PowerConverter.Input.[2].Phase.[23].Voltage", "%.1f", 0 },
	{ "input.bypass.L3-L1.voltage", "UPS.PowerConverter.Input.[2].Phase.[31].Voltage", "%.1f", 0 },
	{ "input.bypass.voltage.nominal", "UPS.Flow.[2].ConfigVoltage", "%.0f", 0 },
	{ "input.bypass.current", "UPS.PowerConverter.Input.[2].Current", "%.2f", 0 },
	{ "input.bypass.L1.current", "UPS.PowerConverter.Input.[2].Phase.[1].Current", "%.1f", 0 },
	{ "input.bypass.L2.current", "UPS.PowerConverter.Input.[2].Phase.[2].Current", "%.1f", 0 },
	{ "input.bypass.L3.current", "UPS.PowerConverter.Input.[2].Phase.[3].Current", "%.1f", 0 },
	{ "input.bypass.current.nominal", "UPS.Flow.[2].ConfigCurrent", "%.2f", 0 },
	{ "input.bypass.frequency", "UPS.PowerConverter.Input.[2].Frequency", "%.1f", 0 },
	{ "input.bypass.frequency.nominal", "UPS.Flow.[2].ConfigFrequency", "%.0f", 0 },
	{ "output.voltage", "UPS.PowerConverter.Output.Voltage", "%.1f", 0 },
	{ "output.L1-N.voltage", "UPS.PowerConverter.Output.Phase.[1].Voltage", "%.1f", 0 },
	{ "output.L2-N.voltage", "UPS.PowerConverter.Output.Phase.[2].Voltage", "%.1f", 0 },
	{ "output.L3-N.voltage", "UPS.PowerConverter.Output.Phase.[3].Voltage", "%.1f", 0 },
	{ "output.L1-L2.voltage", "UPS.PowerConverter.Output.Phase.[12].Voltage", "%.1f", 0 },
	{ "output.L2-L3.voltage", "UPS.PowerConverter.Output.Phase.[23].Voltage", "%.1f", 0 },
	{ "output.L3-L1.voltage", "UPS.PowerConverter.Output.Phase.[31].Voltage", "%.1f", 0 },
	{ "output.current", "UPS.PowerConverter.Output.Current", "%.2f", 0 },
	{ "output.L1.current", "UPS.PowerConverter.Output.Phase.[1].Current", "%.1f", 0 },
	{ "output.L2.current", "UPS.PowerConverter.Output.Phase.[2].Current", "%.1f", 0 },
	{ "output.L3.current", "UPS.PowerConverter.Output.Phase.[3].Current", "%.1f", 0 },
	{ "output.current.nominal", "UPS.Flow.[4].ConfigCurrent", "%.2f", 0 },
	{ "output.frequency", "UPS.PowerConverter.Output.Frequency", "%.1f", 0 },
	{ "output.frequency.nominal", "UPS.Flow.[4].ConfigFrequency", "%.0f", 0 },
	{ "outlet.id", "UPS.OutletSystem.Outlet.[1].OutletID", "%.0f", 0 },
	{ "outlet.desc", "UPS.OutletSystem.Outlet.[1].OutletID", "Main Outlet", 0 },
	{ "outlet.power", "UPS.OutletSystem.Outlet.[1].ApparentPower", "%.0f", 0 },
	{ "outlet.realpower", "UPS.OutletSystem.Outlet.[1].ActivePower", "%.0f", 0 },
	{ "outlet.current", "UPS.OutletSystem.Outlet.[1].Current", "%.2f", 0 },
	{ "outlet.1.id", "UPS.OutletSystem.Outlet.[2].OutletID", "%.0f", 0 },
	{ "outlet.1.desc", "UPS.OutletSystem.Outlet.[2].OutletID", "PowerShare Outlet 1", 0 },
	{ "outlet.1.autoswitch.charge.low", "UPS.OutletSystem.Outlet.[2].RemainingCapacityLimit", "%.0f", 0 },
	{ "outlet.1.delay.shutdown", "UPS.OutletSystem.Outlet.[2].ShutdownTimer", "%.0f", 0 },
	{ "outlet.1.delay.start", "UPS.OutletSystem.Outlet.[2].StartupTimer", "%.0f", 0 },
	{ "outlet.1.power", "UPS.OutletSystem.Outlet.[2].ApparentPower", "%.0f", 0 },
	{ "outlet.1.realpower", "UPS.OutletSystem.Outlet.[2].ActivePower", "%.0f", 0 },
	{ "outlet.1.current", "UPS.OutletSystem.Outlet.[2].Current", "%.2f", 0 },
	{ "outlet.2.id", "UPS.OutletSystem.Outlet.[3].OutletID", "%.0f", 0 },
	{ "outlet.2.desc", "UPS.OutletSystem.Outlet.[3].OutletID", "PowerShare Outlet 2", 0 },
	{ "outlet.2.autoswitch.charge.low", "UPS.OutletSystem.Outlet.[3].RemainingCapacityLimit", "%.0f", 0 },
	{ "outlet.2.delay.shutdown", "UPS.OutletSystem.Outlet.[3].ShutdownTimer", "%.0f", 0 },
	{ "outlet.2.delay.start", "UPS.OutletSystem.Outlet.[3].StartupTimer", "%.0f", 0 },
	{ "outlet.2.power", "UPS.OutletSystem.Outlet.[3].ApparentPower", "%.0f", 0 },
	{ "outlet.2.realpower", "UPS.OutletSystem.Outlet.[3].ActivePower", "%.0f", 0 },
	{ "outlet.2.current", "UPS.OutletSystem.Outlet.[3].Current", "%.2f", 0 },
	{ "outlet.3.id", "UPS.OutletSystem.Outlet.[4].OutletID", "%.0f", 0 },
	{ "outlet.3.desc", "UPS.OutletSystem.Outlet.[4].OutletID", "PowerShare Outlet 2", 0 },
	{ "outlet.3.autoswitch.charge.low", "UPS.OutletSystem.Outlet.[4].RemainingCapacityLimit", "%.0f", 0 },
	{ "outlet.3.delay.shutdown", "UPS.OutletSystem.Outlet.[4].ShutdownTimer", "%.0f", 0 },
	{ "outlet.3.delay.start", "UPS.OutletSystem.Outlet.[4].StartupTimer", "%.0f", 0 },
	{ "outlet.3.power", "UPS.OutletSystem.Outlet.[4].ApparentPower", "%.0f", 0 },
	{ "outlet.3.realpower", "UPS.OutletSystem.Outlet.[4].ActivePower", "%.0f", 0 },
	{ "outlet.3.current", "UPS.OutletSystem.Outlet.[4].Current", "%.2f", 0 },
};

const size_t MGE_READ_MAP_COUNT = sizeof(MGE_READ_MAP) / sizeof(MGE_READ_MAP[0]);

/* BOOL status entries, from mge_hid2nut[]: path plus the ups.status
 * token implied by the upstream hid2info function
 * (online_info -> OL/OB, eaton_discharging_info -> DISCHRG, ...). */
const mge_bool_entry_t MGE_BOOL_MAP[] = {
	{ "UPS.PowerSummary.PresentStatus.ACPresent", "OL", "OB" },
	{ "UPS.PowerSummary.PresentStatus.Discharging", "DISCHRG", NULL },
	{ "UPS.PowerSummary.PresentStatus.Charging", "CHRG", NULL },
	{ "UPS.PowerSummary.PresentStatus.BelowRemainingCapacityLimit", "LB", NULL },
	{ "UPS.PowerConverter.Output.Overload.[1].PresentStatus.OverThreshold", "OVER", NULL },
	{ "UPS.PowerConverter.Output.Overload.[2].PresentStatus.OverThreshold", "OVER", NULL },
	{ "UPS.PowerSummary.PresentStatus.Overload", "OVER", NULL },
	{ "UPS.PowerSummary.PresentStatus.NeedReplacement", "RB", NULL },
	{ "UPS.PowerConverter.Input.[1].PresentStatus.Buck", "TRIM", NULL },
	{ "UPS.PowerConverter.Input.[1].PresentStatus.Boost", "BOOST", NULL },
	{ "UPS.PowerSummary.PresentStatus.Good", NULL, "OFF" },
	{ "UPS.PowerSummary.PresentStatus.ShutdownImminent", "FSD", NULL },
};

const size_t MGE_BOOL_MAP_COUNT = sizeof(MGE_BOOL_MAP) / sizeof(MGE_BOOL_MAP[0]);
